FROM ubuntu:14.04
MAINTAINER sorah

RUN apt-get update && apt-get install -y ruby git-core build-essential automake autoconf bison libffi-dev libgdbm-dev libgmp-dev libncurses5-dev libncursesw5-dev libreadline6-dev libssl-dev libyaml-dev netbase openssl procps zlib1g-dev
RUN mkdir -p /usr/local/bin

ADD setup-rbenv /usr/local/bin/setup-rbenv
RUN /usr/local/bin/setup-rbenv

ADD build /usr/local/bin/build

ENTRYPOINT ["build"]
